### ISSUE TITLE
Installing flash-store v0.12.1 in alpine throws errors: no linux/fs.h

### ISSUE THREAD

**Issue by windmemory** [huan/flash-store#44]
I got errors when building docker images with base container `node:10.15.0-alpine`, here is the error message:

```shell
../deps/leveldb/leveldb-rocksdb/util/io_posix.cc:16:22: fatal error: linux/fs.h: No such file or directory
 #include <linux/fs.h>
                      ^
compilation terminated.
make: *** [deps/leveldb/leveldb.target.mk:299: Release/obj.target/leveldb/deps/leveldb/leveldb-rocksdb/util/io_posix.o] Error 1
```

Searched with google, found that the file is in the `linux-headers` package.

So add `apk add linux-headers` into the docker build file, everything works like a charm.

This issue is to record the problems that I encountered and how I solve it, so people who met the same problem could solve it easily.

**Comment by huan** [comment]
### Solution

after run

```sh
apk add linux-headers
```

then everything works like a charm.

Thank you @windmemory for recording that!
