### ISSUE TITLE
Switch to SnapDB

### ISSUE THREAD

**Issue by huan** [huan/flash-store#45]
[SnapDb](https://github.com/ClickSimply/snap-db) is a Simple & Robust LSM Powered Javascript key-value store with Zero dependencies with pure JavaScript implementation.

Switch to SnapDB will solve #43 and make the installation easy for the end-users who have no build tool installed.

**Comment by huan** [comment]
Some improvements need to be done before we can be able to switch:

1. https://github.com/ClickSimply/snap-db/issues/1
1. https://github.com/ClickSimply/snap-db/issues/2

**Comment by only-cliches** [comment]
Was reading through the code and noticed you guys needed a few other things.

https://github.com/huan/flash-store/blob/8ad5357fca3d7c1e747e970c6316ebc04f5f356e/src/flash-store.ts#L76

https://github.com/huan/flash-store/blob/8ad5357fca3d7c1e747e970c6316ebc04f5f356e/src/flash-store.ts#L198

I added support for `any` key types and a new `.exists` method in SnapDB `1.1.5`, just released.

Just keep in mind even in `any` mode provided keys must be a string or number, everything else will be stringified before being saved to disk.

Hope that helps you guys out!

**Comment by huan** [comment]
Awesome! Thank you for the great improvement, will update the code later!

**Comment by huan** [comment]
We were able to get rid of all the `as any` in the code with the help from @ClickSimply.

Appreciate!
